"""add about to artist_profiles

Revision ID: 34c70f87e834
Revises: 9416456c0fd7
Create Date: 2026-09-15 15:29:05.978220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c70f87e834'
down_revision: Union[str, Sequence[str], None] = '9416456c0fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_profiles', sa.Column('about', sa.Text(), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist_profiles', 'about')
    # ### end Alembic commands ###
